worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    gzip on;
    client_max_body_size 500m;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;

    include /etc/nginx/conf.d/igar.conf;
}
